server:
  port: 8081

spring:
  application:
    name: ferrick-harmony-notification

  datasource:
    url: jdbc:postgresql://localhost:5434/ferrick-harmony-notification
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  flyway:
    enabled: false